# Generated by Django 6.0.3 on 2026-03-30 22:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stockdata_stock_wishlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishlistItem',
            new_name='Wishlist',
        ),
    ]
