# Generated by Django 6.0.3 on 2026-04-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
