# Generated by Django 6.0.3 on 2026-04-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_syncjoblock"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="stock",
            table="stocks",
        ),
        migrations.AlterModelTable(
            name="stockdata",
            table="stock_data",
        ),
        migrations.AlterModelTable(
            name="wishlist",
            table="wishlists",
        ),
        migrations.AlterModelTable(
            name="syncjoblock",
            table="sync_job_locks",
        ),
    ]
