from dataclasses import dataclass


DAILY_FIELD_MAP = {
    "recommend_all": "Recommend.All",
    "recommend_ma": "Recommend.MA",
    "recommend_other": "Recommend.Other",
    "rsi": "RSI",
    "yesterday_rsi": "RSI[1]",
    "stoch_k": "Stoch.K",
    "stoch_d": "Stoch.D",
    "yesterday_stoch_k": "Stoch.K[1]",
    "yesterday_stoch_d": "Stoch.D[1]",
    "commodity_channel_index": "CCI20",
    "yesterday_commodity_channel_index": "CCI20[1]",
    "adx": "ADX",
    "adx_di_positive": "ADX+DI",
    "adx_di_negative": "ADX-DI",
    "yesterday_adx_di_positive": "ADX+DI[1]",
    "yesterday_adx_di_negative": "ADX-DI[1]",
    "awesome_oscillator": "AO",
    "yesterday_awesome_oscillator": "AO[1]",
    "two_days_ago_awesome_oscillator": "AO[2]",
    "momentum": "Mom",
    "yesterday_momentum": "Mom[1]",
    "stoch_rsi": "Stoch.RSI.K",
    "stoch_rsi_k": "Stoch.RSI.K",
    "williams_r_recommendation": "Rec.WR",
    "williams_r": "W.R",
    "bollinger_bands_recommendation": "Rec.BBPower",
    "bollinger_bands_power": "BBPower",
    "bollinger_bands_lower": "BB.lower",
    "bollinger_bands_upper": "BB.upper",
    "ultimate_oscillator_recommendation": "Rec.UO",
    "ultimate_oscillator": "UO",
    "ema_5": "EMA5",
    "ema_10": "EMA10",
    "ema_20": "EMA20",
    "ema_30": "EMA30",
    "ema_50": "EMA50",
    "ema_100": "EMA100",
    "ema_200": "EMA200",
    "sma_5": "SMA5",
    "sma_10": "SMA10",
    "sma_20": "SMA20",
    "sma_30": "SMA30",
    "sma_50": "SMA50",
    "sma_100": "SMA100",
    "sma_200": "SMA200",
    "ichimoku_recommendation": "Rec.Ichimoku",
    "ichimoku_base_line": "Ichimoku.BLine",
    "volume_weighted_moving_average_recommendation": "Rec.VWMA",
    "volume_weighted_moving_average": "VWMA",
    "hull_moving_average_recommendation": "Rec.HullMA9",
    "hull_moving_average": "HullMA9",
    "pivot_classic_s3": "Pivot.M.Classic.S3",
    "pivot_classic_s2": "Pivot.M.Classic.S2",
    "pivot_classic_s1": "Pivot.M.Classic.S1",
    "pivot_classic_middle": "Pivot.M.Classic.Middle",
    "pivot_classic_r1": "Pivot.M.Classic.R1",
    "pivot_classic_r2": "Pivot.M.Classic.R2",
    "pivot_classic_r3": "Pivot.M.Classic.R3",
    "pivot_fibonacci_s3": "Pivot.M.Fibonacci.S3",
    "pivot_fibonacci_s2": "Pivot.M.Fibonacci.S2",
    "pivot_fibonacci_s1": "Pivot.M.Fibonacci.S1",
    "pivot_fibonacci_middle": "Pivot.M.Fibonacci.Middle",
    "pivot_fibonacci_r1": "Pivot.M.Fibonacci.R1",
    "pivot_fibonacci_r2": "Pivot.M.Fibonacci.R2",
    "pivot_fibonacci_r3": "Pivot.M.Fibonacci.R3",
    "pivot_camarilla_s3": "Pivot.M.Camarilla.S3",
    "pivot_camarilla_s2": "Pivot.M.Camarilla.S2",
    "pivot_camarilla_s1": "Pivot.M.Camarilla.S1",
    "pivot_camarilla_middle": "Pivot.M.Camarilla.Middle",
    "pivot_camarilla_r1": "Pivot.M.Camarilla.R1",
    "pivot_camarilla_r2": "Pivot.M.Camarilla.R2",
    "pivot_camarilla_r3": "Pivot.M.Camarilla.R3",
    "pivot_woodie_s3": "Pivot.M.Woodie.S3",
    "pivot_woodie_s2": "Pivot.M.Woodie.S2",
    "pivot_woodie_s1": "Pivot.M.Woodie.S1",
    "pivot_woodie_middle": "Pivot.M.Woodie.Middle",
    "pivot_woodie_r1": "Pivot.M.Woodie.R1",
    "pivot_woodie_r2": "Pivot.M.Woodie.R2",
    "pivot_woodie_r3": "Pivot.M.Woodie.R3",
    "pivot_demark_s1": "Pivot.M.Demark.S1",
    "pivot_demark_middle": "Pivot.M.Demark.Middle",
    "pivot_demark_r1": "Pivot.M.Demark.R1",
    "parabolic_sar": "P.SAR",
    "price_change": "change",
    "open": "open",
    "close": "close",
    "high": "high",
    "low": "low",
    "volume": "volume",
}

RATE_LIMIT_MARKERS = (
    "429",
    "rate limit",
    "too many requests",
)

RETRYABLE_ERROR_MARKERS = (
    *RATE_LIMIT_MARKERS,
    "timeout",
    "timed out",
    "connection reset",
    "temporarily unavailable",
    "expecting value: line 1 column 1 (char 0)",
)


@dataclass(frozen=True)
class TokenSyncConfig:
    max_batches_per_run: int = 10
    delay_between_interval_requests_seconds: int = 45
    delay_between_batch_requests_seconds: int = 15
    delay_between_single_symbol_requests_seconds: int = 30
    max_batch_retries: int = 1
    max_single_retries: int = 1
    retry_delay_seconds: int = 30
    timeout: int | None = None
